### ISSUE TITLE
Error while reading clock name

### ISSUE THREAD

**Issue by simark** [efficios/pytsdl#2]
While trying to parse the TSDL document show later, I am getting this error:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    p.parse(tsdl)
  File "/home/simark/src/lttng-analyses/tests/integration/env/lib/python3.5/site-packages/pytsdl/parser.py", line 1907, in parse
    ast.accept(visitor)
  File "/home/simark/src/lttng-analyses/tests/integration/env/lib/python3.5/site-packages/pytsdl/parser.py", line 68, in accept
    return getattr(visitor, method)(self)
  File "/home/simark/src/lttng-analyses/tests/integration/env/lib/python3.5/site-packages/pytsdl/parser.py", line 1365, in visit_Top
    self._visit_scope(node, self._doc)
  File "/home/simark/src/lttng-analyses/tests/integration/env/lib/python3.5/site-packages/pytsdl/parser.py", line 1306, in _visit_scope
    entry.accept(self)
  File "/home/simark/src/lttng-analyses/tests/integration/env/lib/python3.5/site-packages/pytsdl/parser.py", line 68, in accept
    return getattr(visitor, method)(self)
  File "/home/simark/src/lttng-analyses/tests/integration/env/lib/python3.5/site-packages/pytsdl/parser.py", line 1417, in visit_Clock
    clock = self._visit_scope(node, pytsdl.tsdl.Clock())
  File "/home/simark/src/lttng-analyses/tests/integration/env/lib/python3.5/site-packages/pytsdl/parser.py", line 1306, in _visit_scope
    entry.accept(self)
  File "/home/simark/src/lttng-analyses/tests/integration/env/lib/python3.5/site-packages/pytsdl/parser.py", line 68, in accept
    return getattr(visitor, method)(self)
  File "/home/simark/src/lttng-analyses/tests/integration/env/lib/python3.5/site-packages/pytsdl/parser.py", line 1596, in visit_ValueAssignment
    self._value_assignment_map[type(obj)](key, value)
  File "/home/simark/src/lttng-analyses/tests/integration/env/lib/python3.5/site-packages/pytsdl/parser.py", line 1497, in _value_assign_clock
    clock.name = value[0].value
TypeError: 'LiteralString' object does not support indexing
```

```
/* CTF 1.8 */

typealias integer { size = 8; align = 8; signed = false; } := uint8_t;
typealias integer { size = 16; align = 8; signed = false; } := uint16_t;
typealias integer { size = 32; align = 8; signed = false; } := uint32_t;
typealias integer { size = 64; align = 8; signed = false; } := uint64_t;
typealias integer { size = 64; align = 8; signed = false; } := unsigned long;
typealias integer { size = 5; align = 1; signed = false; } := uint5_t;
typealias integer { size = 27; align = 1; signed = false; } := uint27_t;

trace {
	major = 1;
	minor = 8;
	uuid = "f434dd60-c44b-4ace-9f3e-6eafeae60cc3";
	byte_order = le;
	packet.header := struct {
		uint32_t magic;
		uint8_t  uuid[16];
		uint32_t stream_id;
		uint64_t stream_instance_id;
	};
};

env {
	hostname = "simark";
	domain = "ust";
	tracer_name = "lttng-ust";
	tracer_major = 2;
	tracer_minor = 8;
};

clock {
	name = "monotonic";
	uuid = "16d435c2-df94-4363-b445-1608604824fa";
	description = "Monotonic Clock";
	freq = 1000000000; /* Frequency, in Hz */
	/* clock value offset from Epoch is: offset * (1/freq) */
	offset = 1463892040241446634;
};

typealias integer {
	size = 27; align = 1; signed = false;
	map = clock.monotonic.value;
} := uint27_clock_monotonic_t;

typealias integer {
	size = 32; align = 8; signed = false;
	map = clock.monotonic.value;
} := uint32_clock_monotonic_t;

typealias integer {
	size = 64; align = 8; signed = false;
	map = clock.monotonic.value;
} := uint64_clock_monotonic_t;

struct packet_context {
	uint64_clock_monotonic_t timestamp_begin;
	uint64_clock_monotonic_t timestamp_end;
	uint64_t content_size;
	uint64_t packet_size;
	uint64_t packet_seq_num;
	unsigned long events_discarded;
	uint32_t cpu_id;
};

struct event_header_compact {
	enum : uint5_t { compact = 0 ... 30, extended = 31 } id;
	variant <id> {
		struct {
			uint27_clock_monotonic_t timestamp;
		} compact;
		struct {
			uint32_t id;
			uint64_clock_monotonic_t timestamp;
		} extended;
	} v;
} align(8);

struct event_header_large {
	enum : uint16_t { compact = 0 ... 65534, extended = 65535 } id;
	variant <id> {
		struct {
			uint32_clock_monotonic_t timestamp;
		} compact;
		struct {
			uint32_t id;
			uint64_clock_monotonic_t timestamp;
		} extended;
	} v;
} align(8);

stream {
	id = 0;
	event.header := struct event_header_compact;
	packet.context := struct packet_context;
	event.context := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _vpid;
		integer { size = 64; align = 8; signed = 0; encoding = none; base = 16; } _ip;
	};
};

event {
	name = "lttng_ust_statedump:start";
	id = 0;
	stream_id = 0;
	loglevel = 13;
	fields := struct {
	};
};

event {
	name = "lttng_ust_statedump:bin_info";
	id = 1;
	stream_id = 0;
	loglevel = 13;
	fields := struct {
		integer { size = 64; align = 8; signed = 0; encoding = none; base = 16; } _baddr;
		integer { size = 64; align = 8; signed = 0; encoding = none; base = 10; } _memsz;
		string _path;
		integer { size = 8; align = 8; signed = 0; encoding = none; base = 10; } _is_pic;
		integer { size = 8; align = 8; signed = 0; encoding = none; base = 10; } _has_build_id;
		integer { size = 8; align = 8; signed = 0; encoding = none; base = 10; } _has_debug_link;
	};
};

event {
	name = "lttng_ust_statedump:build_id";
	id = 2;
	stream_id = 0;
	loglevel = 13;
	fields := struct {
		integer { size = 64; align = 8; signed = 0; encoding = none; base = 16; } _baddr;
		integer { size = 64; align = 8; signed = 0; encoding = none; base = 10; } __build_id_length;
		integer { size = 8; align = 8; signed = 0; encoding = none; base = 16; } _build_id[ __build_id_length ];
	};
};

event {
	name = "lttng_ust_statedump:debug_link";
	id = 3;
	stream_id = 0;
	loglevel = 13;
	fields := struct {
		integer { size = 64; align = 8; signed = 0; encoding = none; base = 16; } _baddr;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } _crc;
		string _filename;
	};
};

event {
	name = "lttng_ust_statedump:end";
	id = 4;
	stream_id = 0;
	loglevel = 13;
	fields := struct {
	};
};

event {
	name = "lttng_ust_tracef:event";
	id = 5;
	stream_id = 0;
	loglevel = 14;
	fields := struct {
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_EMERG";
	id = 6;
	stream_id = 0;
	loglevel = 0;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_ALERT";
	id = 7;
	stream_id = 0;
	loglevel = 1;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_CRIT";
	id = 8;
	stream_id = 0;
	loglevel = 2;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_ERR";
	id = 9;
	stream_id = 0;
	loglevel = 3;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_WARNING";
	id = 10;
	stream_id = 0;
	loglevel = 4;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_NOTICE";
	id = 11;
	stream_id = 0;
	loglevel = 5;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_INFO";
	id = 12;
	stream_id = 0;
	loglevel = 6;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_DEBUG_SYSTEM";
	id = 13;
	stream_id = 0;
	loglevel = 7;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_DEBUG_PROGRAM";
	id = 14;
	stream_id = 0;
	loglevel = 8;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_DEBUG_PROCESS";
	id = 15;
	stream_id = 0;
	loglevel = 9;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_DEBUG_MODULE";
	id = 16;
	stream_id = 0;
	loglevel = 10;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_DEBUG_UNIT";
	id = 17;
	stream_id = 0;
	loglevel = 11;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_DEBUG_FUNCTION";
	id = 18;
	stream_id = 0;
	loglevel = 12;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_DEBUG_LINE";
	id = 19;
	stream_id = 0;
	loglevel = 13;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_tracelog:TRACE_DEBUG";
	id = 20;
	stream_id = 0;
	loglevel = 14;
	fields := struct {
		integer { size = 32; align = 8; signed = 1; encoding = none; base = 10; } _line;
		string _file;
		string _func;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } __msg_length;
		integer { size = 8; align = 8; signed = 1; encoding = UTF8; base = 10; } _msg[ __msg_length ];
	};
};

event {
	name = "lttng_ust_dl:dlopen";
	id = 21;
	stream_id = 0;
	loglevel = 13;
	fields := struct {
		integer { size = 64; align = 8; signed = 0; encoding = none; base = 16; } _baddr;
		integer { size = 64; align = 8; signed = 0; encoding = none; base = 10; } _memsz;
		string _path;
		integer { size = 8; align = 8; signed = 0; encoding = none; base = 10; } _has_build_id;
		integer { size = 8; align = 8; signed = 0; encoding = none; base = 10; } _has_debug_link;
	};
};

event {
	name = "lttng_ust_dl:build_id";
	id = 22;
	stream_id = 0;
	loglevel = 13;
	fields := struct {
		integer { size = 64; align = 8; signed = 0; encoding = none; base = 16; } _baddr;
		integer { size = 64; align = 8; signed = 0; encoding = none; base = 10; } __build_id_length;
		integer { size = 8; align = 8; signed = 0; encoding = none; base = 16; } _build_id[ __build_id_length ];
	};
};

event {
	name = "lttng_ust_dl:debug_link";
	id = 23;
	stream_id = 0;
	loglevel = 13;
	fields := struct {
		integer { size = 64; align = 8; signed = 0; encoding = none; base = 16; } _baddr;
		integer { size = 32; align = 8; signed = 0; encoding = none; base = 10; } _crc;
		string _filename;
	};
};

event {
	name = "lttng_ust_dl:dlclose";
	id = 24;
	stream_id = 0;
	loglevel = 13;
	fields := struct {
		integer { size = 64; align = 8; signed = 0; encoding = none; base = 16; } _baddr;
	};
};
```

**Comment by eepp** [comment]
For this, and for #3, and for future issues: this project is not maintained anymore. It was designed mostly to parse the input language of barectf 0.x, which is also not maintained anymore (the 0.x line).

You're welcome to take the ownership by the way!

**Comment by simark** [comment]
This saddens me very deeply.
